In [3]:
import pandas as pd
import numpy as np
import matplotlib as pyplot
import seaborn as sns
print("Successfully installed!")

Successfully installed!

In [4]:
df = pd.read_csv("/Users/shreyasjoshi/Desktop/Masters/Summer_Course/data.csv", encoding='ISO-8859-1')

In [5]:
print(df.shape)
df.head(5)

(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None

In [7]:
print(df.describe())

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [8]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Description      1454
CustomerID     135080
dtype: int64

In [9]:
print(df['Country'].value_counts())

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [10]:
print(df['StockCode'].value_counts())

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
21431        1
22275        1
17001        1
90187A       1
72759        1
Name: count, Length: 4070, dtype: int64

In [11]:
df['Description'].value_counts()

Description
WHITE HANGING HEART T-LIGHT HOLDER     2369
REGENCY CAKESTAND 3 TIER               2200
JUMBO BAG RED RETROSPOT                2159
PARTY BUNTING                          1727
LUNCH BAG RED RETROSPOT                1638
                                       ...
Missing                                   1
historic computer difference?....se       1
DUSTY PINK CHRISTMAS TREE 30CM            1
WRAP BLUE RUSSIAN FOLKART                 1
PINK BERTIE MOBILE PHONE CHARM            1
Name: count, Length: 4223, dtype: int64

In [12]:
df['Country'].value_counts(dropna=False)

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [13]:
df['StockCode'].value_counts(dropna=False)

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
21431        1
22275        1
17001        1
90187A       1
72759        1
Name: count, Length: 4070, dtype: int64

In [14]:
df['Description'].value_counts(dropna=False)

Description
WHITE HANGING HEART T-LIGHT HOLDER     2369
REGENCY CAKESTAND 3 TIER               2200
JUMBO BAG RED RETROSPOT                2159
PARTY BUNTING                          1727
LUNCH BAG RED RETROSPOT                1638
                                       ...
Missing                                   1
historic computer difference?....se       1
DUSTY PINK CHRISTMAS TREE 30CM            1
WRAP BLUE RUSSIAN FOLKART                 1
PINK BERTIE MOBILE PHONE CHARM            1
Name: count, Length: 4224, dtype: int64

In [15]:
print(df[['Country', 'StockCode', 'Description']].nunique())

Country          38
StockCode      4070
Description    4223
dtype: int64

In [16]:
print(df[['Quantity', 'UnitPrice']].agg(['min', 'max', 'sum', 'mean', 'count']))

           Quantity     UnitPrice
min   -8.099500e+04 -1.106206e+04
max    8.099500e+04  3.897000e+04
sum    5.176450e+06  2.498804e+06
mean   9.552250e+00  4.611114e+00
count  5.419090e+05  5.419090e+05

In [17]:
print(f"Negative Quantities (Returns): {(df['Quantity'] < 0).sum()}")
print(f"Zero or Negative Prices: {(df['UnitPrice'] <= 0).sum()}")
invalid_sales = df[(df['Quantity'] < 0) | (df['UnitPrice'] <= 0)]
invalid_sales.head()

Negative Quantities (Returns): 10624
Zero or Negative Prices: 2517

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom

In [18]:
region_dict = {
    'United Kingdom': 'UK&IE',
    'EIRE': 'UK&IE',
    'France': 'Western Europe',
    'Germany': 'Western Europe',
    'Netherlands': 'Western Europe',
    'Spain': 'Southern Europe',
    'Portugal': 'Southern Europe',
    'Italy': 'Southern Europe',
    'Australia': 'AsiaPacific',
    'Japan': 'AsiaPacific'
}
lookup = pd.DataFrame(list(region_dict.items()), columns=['Country', 'Region'])
print(lookup)

          Country           Region
0  United Kingdom            UK&IE
1            EIRE            UK&IE
2          France   Western Europe
3         Germany   Western Europe
4     Netherlands   Western Europe
5           Spain  Southern Europe
6        Portugal  Southern Europe
7           Italy  Southern Europe
8       Australia      AsiaPacific
9           Japan      AsiaPacific

In [19]:
df.iloc[10:15, 0:4]

   InvoiceNo StockCode                         Description  Quantity
10    536367     22745          POPPY'S PLAYHOUSE BEDROOM          6
11    536367     22748           POPPY'S PLAYHOUSE KITCHEN         6
12    536367     22749   FELTCRAFT PRINCESS CHARLOTTE DOLL         8
13    536367     22310             IVORY KNITTED MUG COSY          6
14    536367     84969  BOX OF 6 ASSORTED COLOUR TEASPOONS         6

In [20]:
df['LineRevenue'] = df['Quantity'] * df['UnitPrice']
print(df.sort_values(by='LineRevenue', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))
print(df.sort_values(by='LineRevenue', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))

       InvoiceNo                     Description  Quantity  UnitPrice  \
540421    581483     PAPER CRAFT , LITTLE BIRDIE     80995       2.08
61619     541431  MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
222680    556444  PICNIC BASKET WICKER 60 PIECES        60     649.50
15017     537632                      AMAZON FEE         1   13541.33
299982   A563185                 Adjust bad debt         1   11062.06

        LineRevenue
540421    168469.60
61619      77183.60
222680     38970.00
15017      13541.33
299982     11062.06
       InvoiceNo                     Description  Quantity  UnitPrice  \
540422   C581484     PAPER CRAFT , LITTLE BIRDIE    -80995       2.08
61624    C541433  MEDIUM CERAMIC TOP STORAGE JAR    -74215       1.04
222681   C556445                          Manual        -1   38970.00
524602   C580605                      AMAZON FEE        -1   17836.46
43702    C540117                      AMAZON FEE        -1   16888.02

        LineRevenue
540422   -168469.60
61624     -77183.60
222681    -38970.00
524602    -17836.46
43702     -16888.02

In [21]:
df['LineRevenue'] = df['Quantity'] * df['UnitPrice']
print(df.sort_values(by='LineRevenue', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))
print(df.sort_values(by='LineRevenue', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))

       InvoiceNo                     Description  Quantity  UnitPrice  \
540421    581483     PAPER CRAFT , LITTLE BIRDIE     80995       2.08
61619     541431  MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
222680    556444  PICNIC BASKET WICKER 60 PIECES        60     649.50
15017     537632                      AMAZON FEE         1   13541.33
299982   A563185                 Adjust bad debt         1   11062.06

        LineRevenue
540421    168469.60
61619      77183.60
222680     38970.00
15017      13541.33
299982     11062.06
       InvoiceNo                     Description  Quantity  UnitPrice  \
540422   C581484     PAPER CRAFT , LITTLE BIRDIE    -80995       2.08
61624    C541433  MEDIUM CERAMIC TOP STORAGE JAR    -74215       1.04
222681   C556445                          Manual        -1   38970.00
524602   C580605                      AMAZON FEE        -1   17836.46
43702    C540117                      AMAZON FEE        -1   16888.02

        LineRevenue
540422   -168469.60
61624     -77183.60
222681    -38970.00
524602    -17836.46
43702     -16888.02

In [22]:
df.index = [f"item_{i}" for i in range(len(df))]
df.loc['item_100':'item_105']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,LineRevenue
item_100,536378,84519A,TOMATO CHARLIE+LOLA COASTER SET,6,12/1/2010 9:37,2.95,14688.0,United Kingdom,17.70
item_101,536378,85183B,CHARLIE & LOLA WASTEPAPER BIN FLORA,48,12/1/2010 9:37,1.25,14688.0,United Kingdom,60.00
item_102,536378,85071B,RED CHARLIE+LOLA PERSONAL DOORSIGN,96,12/1/2010 9:37,0.38,14688.0,United Kingdom,36.48
item_103,536378,21931,JUMBO STORAGE BAG SUKI,10,12/1/2010 9:37,1.95,14688.0,United Kingdom,19.50
item_104,536378,21929,JUMBO BAG PINK VINTAGE PAISLEY,10,12/1/2010 9:37,1.95,14688.0,United Kingdom,19.50
item_105,536380,22961,JAM MAKING SET PRINTED,24,12/1/2010 9:41,1.45,17809.0,United Kingdom,34.80

In [23]:
cancel = df[df['InvoiceNo'].astype(str).str.startswith('C', na=False)]
invalid = df[df['Quantity'] <= 0]
invalidp = df[df['UnitPrice'] <= 0]

# Print the explicit counts for each isolated group
print(f"Total Cancellations (Starts with 'C'): {len(cancel)}")
print(f"Rows where Quantity less/equal to 0: {len(invalid)}")
print(f"Rows where UnitPrice less/equal 0: {len(invalidp)}")

Total Cancellations (Starts with 'C'): 9288
Rows where Quantity less/equal to 0: 10624
Rows where UnitPrice less/equal 0: 2517

In [24]:
df['LineRevenue'] = df['Quantity'] * df['UnitPrice']
print(df.sort_values(by='LineRevenue', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))
print(df.sort_values(by='LineRevenue', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))

            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540421    581483     PAPER CRAFT , LITTLE BIRDIE     80995       2.08
item_61619     541431  MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
item_222680    556444  PICNIC BASKET WICKER 60 PIECES        60     649.50
item_15017     537632                      AMAZON FEE         1   13541.33
item_299982   A563185                 Adjust bad debt         1   11062.06

             LineRevenue
item_540421    168469.60
item_61619      77183.60
item_222680     38970.00
item_15017      13541.33
item_299982     11062.06
            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540422   C581484     PAPER CRAFT , LITTLE BIRDIE    -80995       2.08
item_61624    C541433  MEDIUM CERAMIC TOP STORAGE JAR    -74215       1.04
item_222681   C556445                          Manual        -1   38970.00
item_524602   C580605                      AMAZON FEE        -1   17836.46
item_43702    C540117                      AMAZON FEE        -1   16888.02

             LineRevenue
item_540422   -168469.60
item_61624     -77183.60
item_222681    -38970.00
item_524602    -17836.46
item_43702     -16888.02

In [25]:

print(df.sort_values(by='Quantity', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice']].head(5))
print(df.sort_values(by='Quantity', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice']].head(5))
df['LineRevenue'] = df['Quantity'] * df['UnitPrice']
print(df.sort_values(by='LineRevenue', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))
print(df.sort_values(by='LineRevenue', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))

            InvoiceNo                        Description  Quantity  UnitPrice
item_540421    581483        PAPER CRAFT , LITTLE BIRDIE     80995       2.08
item_61619     541431     MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
item_502122    578841     ASSTD DESIGN 3D PAPER STICKERS     12540       0.00
item_74614     542504                                NaN      5568       0.00
item_421632    573008  WORLD WAR 2 GLIDERS ASSTD DESIGNS      4800       0.21
            InvoiceNo                          Description  Quantity  \
item_540422   C581484          PAPER CRAFT , LITTLE BIRDIE    -80995
item_61624    C541433       MEDIUM CERAMIC TOP STORAGE JAR    -74215
item_225529    556690         printing smudges/thrown away     -9600
item_225530    556691         printing smudges/thrown away     -9600
item_4287     C536757  ROTATING SILVER ANGELS T-LIGHT HLDR     -9360

             UnitPrice
item_540422       2.08
item_61624        1.04
item_225529       0.00
item_225530       0.00
item_4287         0.03
            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540421    581483     PAPER CRAFT , LITTLE BIRDIE     80995       2.08
item_61619     541431  MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
item_222680    556444  PICNIC BASKET WICKER 60 PIECES        60     649.50
item_15017     537632                      AMAZON FEE         1   13541.33
item_299982   A563185                 Adjust bad debt         1   11062.06

             LineRevenue
item_540421    168469.60
item_61619      77183.60
item_222680     38970.00
item_15017      13541.33
item_299982     11062.06
            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540422   C581484     PAPER CRAFT , LITTLE BIRDIE    -80995       2.08
item_61624    C541433  MEDIUM CERAMIC TOP STORAGE JAR    -74215       1.04
item_222681   C556445                          Manual        -1   38970.00
item_524602   C580605                      AMAZON FEE        -1   17836.46
item_43702    C540117                      AMAZON FEE        -1   16888.02

             LineRevenue
item_540422   -168469.60
item_61624     -77183.60
item_222681    -38970.00
item_524602    -17836.46
item_43702     -16888.02

In [ ]:
# 3.6 Replacing values
part1_df = df.copy().reset_index(drop=True)

country_replacements = {
    'EIRE': 'Ireland',
    'RSA': 'South Africa',
    'Unspecified': np.nan
}
part1_df['Country'] = part1_df['Country'].replace(country_replacements)
part1_df['Country'].value_counts(dropna=False)

In [ ]:
# 3.7 Renaming columns
rename_map = {
    'InvoiceNo': 'invoice_no',
    'StockCode': 'stock_code',
    'Description': 'description',
    'Quantity': 'quantity',
    'InvoiceDate': 'invoice_date',
    'UnitPrice': 'unit_price',
    'CustomerID': 'customer_id',
    'Country': 'country',
    'LineRevenue': 'line_revenue'
}
part1_df = part1_df.rename(columns=rename_map)
part1_df.head()

In [ ]:
# 3.10 Handling missing values
missing_summary = pd.DataFrame({
    'missing_count': part1_df.isnull().sum(),
    'missing_percent': (part1_df.isnull().mean() * 100).round(2)
}).query('missing_count > 0')

customer_id_dropna_demo = part1_df.dropna(subset=['customer_id'])
description_dropna_demo = part1_df.dropna(subset=['description'])
description_fillna_demo = part1_df['description'].fillna('Unknown Product')

part1_df['customer_id_missing'] = part1_df['customer_id'].isnull()
part1_df['description'] = part1_df['description'].fillna('Unknown Product')

missing_policy = pd.DataFrame({
    'column': ['customer_id', 'description'],
    'policy': [
        'keep missing customer_id for sales analysis; exclude only for customer-level summaries',
        'fill missing description for profiling, then remove unknown product rows from final sales data'
    ]
})

missing_summary

In [ ]:
# 3.11 Deleting a column
columns_to_drop = [col for col in ['line_revenue'] if col in part1_df.columns]
dropped_column_log = pd.DataFrame({
    'dropped_column': columns_to_drop,
    'reason': ['recreated as revenue after final cleaning'] * len(columns_to_drop)
})
part1_df = part1_df.drop(columns=columns_to_drop, errors='ignore')
dropped_column_log

In [ ]:
# 3.12 Deleting a row
non_product_codes = {
    'POST', 'DOT', 'M', 'BANK CHARGES', 'AMAZONFEE',
    'D', 'C2', 'S', 'PADS', 'CRUK'
}

is_cancelled = part1_df['invoice_no'].astype(str).str.startswith('C', na=False)
bad_quantity = part1_df['quantity'] <= 0
bad_price = part1_df['unit_price'] <= 0
unknown_description = part1_df['description'].astype(str).str.strip().eq('Unknown Product')
blank_description = part1_df['description'].astype(str).str.strip().eq('')
non_product_line = part1_df['stock_code'].astype(str).str.upper().isin(non_product_codes)

remove_rows = (
    is_cancelled |
    bad_quantity |
    bad_price |
    unknown_description |
    blank_description |
    non_product_line
)

sales_df = part1_df.loc[~remove_rows].copy()

row_removal_summary = pd.Series({
    'start_rows': len(part1_df),
    'cancelled_invoice_rows': int(is_cancelled.sum()),
    'quantity_less_equal_zero_rows': int(bad_quantity.sum()),
    'unit_price_less_equal_zero_rows': int(bad_price.sum()),
    'unknown_or_blank_description_rows': int((unknown_description | blank_description).sum()),
    'non_product_rows': int(non_product_line.sum()),
    'rows_removed_by_filter': int(remove_rows.sum()),
    'sales_rows_before_duplicates': len(sales_df)
})

row_removal_summary

In [ ]:
# 3.13 Dropping duplicates
exact_duplicate_count = sales_df.duplicated().sum()
clean_sales = sales_df.drop_duplicates().copy()
rows_dropped_duplicates = len(sales_df) - len(clean_sales)

pd.Series({
    'exact_duplicates_before_drop': int(exact_duplicate_count),
    'rows_dropped_duplicates': int(rows_dropped_duplicates),
    'clean_sales_rows': len(clean_sales)
})

In [ ]:
# 3.18 Applying a function
clean_sales['revenue'] = clean_sales['quantity'] * clean_sales['unit_price']
clean_sales['description'] = clean_sales['description'].apply(lambda x: str(x).strip().title())
clean_sales['is_cancelled'] = clean_sales['invoice_no'].apply(lambda x: str(x).startswith('C'))

clean_sales[['invoice_no', 'stock_code', 'description', 'quantity', 'unit_price', 'revenue', 'is_cancelled']].head()

In [ ]:
# 3.17 Looping over a column
sample_descriptions = clean_sales['description'].head(10)

loop_cleaned_descriptions = []
for item in sample_descriptions:
    loop_cleaned_descriptions.append(str(item).strip().title())

list_comprehension_flags = [str(item).startswith('C') for item in part1_df['invoice_no'].head(10)]
apply_flags = part1_df['invoice_no'].head(10).apply(lambda x: str(x).startswith('C')).tolist()

looping_comparison = pd.DataFrame({
    'invoice_no': part1_df['invoice_no'].head(10).tolist(),
    'list_comprehension_flag': list_comprehension_flags,
    'apply_flag': apply_flags
})

looping_note = 'apply keeps the operation inside the pandas workflow; vectorized string methods are best when available.'
looping_comparison

In [ ]:
# 3.14 Grouping by values
revenue_by_country = clean_sales.groupby('country')['revenue'].sum().sort_values(ascending=False)
orders_per_customer = (
    clean_sales.dropna(subset=['customer_id'])
    .groupby('customer_id')['invoice_no']
    .nunique()
    .sort_values(ascending=False)
)

revenue_by_country.head(10)

In [ ]:
# 3.16 Aggregating
invoice_totals = clean_sales.groupby(['country', 'invoice_no'], as_index=False)['revenue'].sum()
country_agg = (
    invoice_totals.groupby('country')
    .agg(
        total_revenue=('revenue', 'sum'),
        mean_order_value=('revenue', 'mean'),
        transaction_count=('invoice_no', 'nunique')
    )
    .sort_values('total_revenue', ascending=False)
)

customer_invoice_totals = (
    clean_sales.dropna(subset=['customer_id'])
    .groupby(['customer_id', 'invoice_no'], as_index=False)['revenue']
    .sum()
)
customer_agg = (
    customer_invoice_totals.groupby('customer_id')
    .agg(
        total_revenue=('revenue', 'sum'),
        mean_order_value=('revenue', 'mean'),
        transaction_count=('invoice_no', 'nunique')
    )
    .sort_values('total_revenue', ascending=False)
)

country_agg.head(10)

In [ ]:
# 3.19 Applying to groups
def summarize_customer(group):
    dates = pd.to_datetime(group['invoice_date'], errors='coerce')
    return pd.Series({
        'total_spend': group['revenue'].sum(),
        'orders': group['invoice_no'].nunique(),
        'active_months': dates.dt.to_period('M').nunique()
    })

customer_custom_summary = (
    clean_sales.dropna(subset=['customer_id'])
    .groupby('customer_id')
    .apply(summarize_customer, include_groups=False)
    .sort_values('total_spend', ascending=False)
)

customer_custom_summary.head(10)

In [ ]:
# 3.15 Grouping by time
import matplotlib.pyplot as plt

clean_sales['invoice_date'] = pd.to_datetime(clean_sales['invoice_date'], errors='coerce')
clean_sales = clean_sales.dropna(subset=['invoice_date']).copy()

clean_sales_time_indexed = clean_sales.set_index('invoice_date').sort_index()
monthly_revenue = clean_sales_time_indexed['revenue'].resample('ME').sum()
weekly_revenue = clean_sales_time_indexed['revenue'].resample('W').sum()

monthly_revenue.plot(kind='line', title='Monthly Revenue')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.tight_layout()
plt.show()

monthly_revenue

In [ ]:
# 3.20 Concatenating
first_half_sales = clean_sales[clean_sales['invoice_date'] < '2011-07-01'].copy()
second_half_sales = clean_sales[clean_sales['invoice_date'] >= '2011-07-01'].copy()

recombined_sales = pd.concat([first_half_sales, second_half_sales], ignore_index=True)

pd.Series({
    'first_half_rows': len(first_half_sales),
    'second_half_rows': len(second_half_sales),
    'recombined_rows': len(recombined_sales),
    'clean_sales_rows': len(clean_sales)
})

In [ ]:
# 3.21 Merging
if 'lookup' in globals():
    region_lookup = lookup.copy().rename(columns={'Country': 'country', 'Region': 'region'})
    region_lookup['country'] = region_lookup['country'].replace(country_replacements)
else:
    region_lookup = pd.DataFrame({
        'country': ['United Kingdom', 'Ireland', 'France', 'Germany', 'Netherlands', 'Spain', 'Portugal', 'Italy', 'Australia', 'Japan'],
        'region': ['UK&IE', 'UK&IE', 'Western Europe', 'Western Europe', 'Western Europe', 'Southern Europe', 'Southern Europe', 'Southern Europe', 'AsiaPacific', 'AsiaPacific']
    })

left_joined_sales = clean_sales.merge(region_lookup, on='country', how='left')
inner_joined_sales = clean_sales.merge(region_lookup, on='country', how='inner')

countries_without_region = sorted(left_joined_sales.loc[left_joined_sales['region'].isnull(), 'country'].dropna().unique())
join_comparison = pd.DataFrame({
    'join_type': ['left', 'inner'],
    'rows': [len(left_joined_sales), len(inner_joined_sales)],
    'matched_regions': [left_joined_sales['region'].notna().sum(), inner_joined_sales['region'].notna().sum()],
    'unmatched_regions': [left_joined_sales['region'].isna().sum(), inner_joined_sales['region'].isna().sum()]
})

clean_sales_with_region = left_joined_sales.copy()
clean_sales_with_region.to_csv('clean_online_retail.csv', index=False)

join_comparison

In [ ]:
# clean dataset
clean_sales_with_region.head()