In [2]:
import pandas as pd
import numpy as np
import matplotlib as pyplot
import seaborn as sns
print("Successfully installed!")

Successfully installed!

In [3]:
df = pd.read_csv("/Users/shreyasjoshi/Desktop/Masters/Summer_Course/data.csv", encoding='ISO-8859-1')

In [12]:
print(df.shape)
df.head(5)

(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB
None

In [14]:
print(df.describe())

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [40]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Description      1454
CustomerID     135080
dtype: int64

In [29]:
print(df['Country'].value_counts())

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [30]:
print(df['StockCode'].value_counts())

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
21431        1
22275        1
17001        1
90187A       1
72759        1
Name: count, Length: 4070, dtype: int64

In [28]:
df['Description'].value_counts()

Description
WHITE HANGING HEART T-LIGHT HOLDER     2369
REGENCY CAKESTAND 3 TIER               2200
JUMBO BAG RED RETROSPOT                2159
PARTY BUNTING                          1727
LUNCH BAG RED RETROSPOT                1638
                                       ...
Missing                                   1
historic computer difference?....se       1
DUSTY PINK CHRISTMAS TREE 30CM            1
WRAP BLUE RUSSIAN FOLKART                 1
PINK BERTIE MOBILE PHONE CHARM            1
Name: count, Length: 4223, dtype: int64

In [25]:
df['Country'].value_counts(dropna=False)

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [32]:
df['StockCode'].value_counts(dropna=False)

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
21431        1
22275        1
17001        1
90187A       1
72759        1
Name: count, Length: 4070, dtype: int64

In [ ]:
df['Description'].value_counts(dropna=False)

In [33]:
print(df[['Country', 'StockCode', 'Description']].nunique())

Country          38
StockCode      4070
Description    4223
dtype: int64

In [34]:
print(df[['Quantity', 'UnitPrice']].agg(['min', 'max', 'sum', 'mean', 'count']))

           Quantity     UnitPrice
min   -8.099500e+04 -1.106206e+04
max    8.099500e+04  3.897000e+04
sum    5.176450e+06  2.498804e+06
mean   9.552250e+00  4.611114e+00
count  5.419090e+05  5.419090e+05

In [35]:
print(f"Negative Quantities (Returns): {(df['Quantity'] < 0).sum()}")
print(f"Zero or Negative Prices: {(df['UnitPrice'] <= 0).sum()}")
invalid_sales = df[(df['Quantity'] < 0) | (df['UnitPrice'] <= 0)]
invalid_sales.head()

Negative Quantities (Returns): 10624
Zero or Negative Prices: 2517

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom

In [41]:
region_dict = {
    'United Kingdom': 'UK&IE',
    'EIRE': 'UK&IE',
    'France': 'Western Europe',
    'Germany': 'Western Europe',
    'Netherlands': 'Western Europe',
    'Spain': 'Southern Europe',
    'Portugal': 'Southern Europe',
    'Italy': 'Southern Europe',
    'Australia': 'AsiaPacific',
    'Japan': 'AsiaPacific'
}
lookup = pd.DataFrame(list(region_dict.items()), columns=['Country', 'Region'])
print(lookup)

          Country           Region
0  United Kingdom            UK&IE
1            EIRE            UK&IE
2          France   Western Europe
3         Germany   Western Europe
4     Netherlands   Western Europe
5           Spain  Southern Europe
6        Portugal  Southern Europe
7           Italy  Southern Europe
8       Australia      AsiaPacific
9           Japan      AsiaPacific

In [36]:
df.iloc[10:15, 0:4]

   InvoiceNo StockCode                         Description  Quantity
10    536367     22745          POPPY'S PLAYHOUSE BEDROOM          6
11    536367     22748           POPPY'S PLAYHOUSE KITCHEN         6
12    536367     22749   FELTCRAFT PRINCESS CHARLOTTE DOLL         8
13    536367     22310             IVORY KNITTED MUG COSY          6
14    536367     84969  BOX OF 6 ASSORTED COLOUR TEASPOONS         6

In [ ]:
df['LineRevenue'] = df['Quantity'] * df['UnitPrice']
print(df.sort_values(by='LineRevenue', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))
print(df.sort_values(by='LineRevenue', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))

            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540421    581483     PAPER CRAFT , LITTLE BIRDIE     80995       2.08
item_61619     541431  MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
item_222680    556444  PICNIC BASKET WICKER 60 PIECES        60     649.50
item_15017     537632                      AMAZON FEE         1   13541.33
item_299982   A563185                 Adjust bad debt         1   11062.06

             LineRevenue
item_540421    168469.60
item_61619      77183.60
item_222680     38970.00
item_15017      13541.33
item_299982     11062.06
            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540422   C581484     PAPER CRAFT , LITTLE BIRDIE    -80995       2.08
item_61624    C541433  MEDIUM CERAMIC TOP STORAGE JAR    -74215       1.04
item_222681   C556445                          Manual        -1   38970.00
item_524602   C580605                      AMAZON FEE        -1   17836.46
item_43702    C540117                      AMAZON FEE        -1   16888.02

             LineRevenue
item_540422   -168469.60
item_61624     -77183.60
item_222681    -38970.00
item_524602    -17836.46
item_43702     -16888.02

In [ ]:
df['LineRevenue'] = df['Quantity'] * df['UnitPrice']
print(df.sort_values(by='LineRevenue', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))
print(df.sort_values(by='LineRevenue', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))

            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540421    581483     PAPER CRAFT , LITTLE BIRDIE     80995       2.08
item_61619     541431  MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
item_222680    556444  PICNIC BASKET WICKER 60 PIECES        60     649.50
item_15017     537632                      AMAZON FEE         1   13541.33
item_299982   A563185                 Adjust bad debt         1   11062.06

             LineRevenue
item_540421    168469.60
item_61619      77183.60
item_222680     38970.00
item_15017      13541.33
item_299982     11062.06
            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540422   C581484     PAPER CRAFT , LITTLE BIRDIE    -80995       2.08
item_61624    C541433  MEDIUM CERAMIC TOP STORAGE JAR    -74215       1.04
item_222681   C556445                          Manual        -1   38970.00
item_524602   C580605                      AMAZON FEE        -1   17836.46
item_43702    C540117                      AMAZON FEE        -1   16888.02

             LineRevenue
item_540422   -168469.60
item_61624     -77183.60
item_222681    -38970.00
item_524602    -17836.46
item_43702     -16888.02

In [37]:
df.index = [f"item_{i}" for i in range(len(df))]
df.loc['item_100':'item_105']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
item_100,536378,84519A,TOMATO CHARLIE+LOLA COASTER SET,6,12/1/2010 9:37,2.95,14688.0,United Kingdom
item_101,536378,85183B,CHARLIE & LOLA WASTEPAPER BIN FLORA,48,12/1/2010 9:37,1.25,14688.0,United Kingdom
item_102,536378,85071B,RED CHARLIE+LOLA PERSONAL DOORSIGN,96,12/1/2010 9:37,0.38,14688.0,United Kingdom
item_103,536378,21931,JUMBO STORAGE BAG SUKI,10,12/1/2010 9:37,1.95,14688.0,United Kingdom
item_104,536378,21929,JUMBO BAG PINK VINTAGE PAISLEY,10,12/1/2010 9:37,1.95,14688.0,United Kingdom
item_105,536380,22961,JAM MAKING SET PRINTED,24,12/1/2010 9:41,1.45,17809.0,United Kingdom

In [38]:
cancel = df[df['InvoiceNo'].astype(str).str.startswith('C', na=False)]
invalid = df[df['Quantity'] <= 0]
invalidp = df[df['UnitPrice'] <= 0]

# Print the explicit counts for each isolated group
print(f"Total Cancellations (Starts with 'C'): {len(cancel)}")
print(f"Rows where Quantity less/equal to 0: {len(invalid)}")
print(f"Rows where UnitPrice less/equal 0: {len(invalidp)}")

Total Cancellations (Starts with 'C'): 9288
Rows where Quantity less/equal to 0: 10624
Rows where UnitPrice less/equal 0: 2517

In [39]:
df['LineRevenue'] = df['Quantity'] * df['UnitPrice']
print(df.sort_values(by='LineRevenue', ascending=False)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))
print(df.sort_values(by='LineRevenue', ascending=True)[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'LineRevenue']].head(5))

            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540421    581483     PAPER CRAFT , LITTLE BIRDIE     80995       2.08
item_61619     541431  MEDIUM CERAMIC TOP STORAGE JAR     74215       1.04
item_222680    556444  PICNIC BASKET WICKER 60 PIECES        60     649.50
item_15017     537632                      AMAZON FEE         1   13541.33
item_299982   A563185                 Adjust bad debt         1   11062.06

             LineRevenue
item_540421    168469.60
item_61619      77183.60
item_222680     38970.00
item_15017      13541.33
item_299982     11062.06
            InvoiceNo                     Description  Quantity  UnitPrice  \
item_540422   C581484     PAPER CRAFT , LITTLE BIRDIE    -80995       2.08
item_61624    C541433  MEDIUM CERAMIC TOP STORAGE JAR    -74215       1.04
item_222681   C556445                          Manual        -1   38970.00
item_524602   C580605                      AMAZON FEE        -1   17836.46
item_43702    C540117                      AMAZON FEE        -1   16888.02

             LineRevenue
item_540422   -168469.60
item_61624     -77183.60
item_222681    -38970.00
item_524602    -17836.46
item_43702     -16888.02